[package]
name = "pq-newhope"
version = "0.1.0"
authors = ["Vladislav Melnik <vladislav.melnik@protonmail.com>"]
edition = "2018"

[dependencies]
generic-array = "0.14"
sha3 = "0.8"

[dev-dependencies]
rand = "0.7"
